sentence = """ 
    When he was nearly thirteen my brother Jem got his arm badly broken at the elbow
　　When it healed and Jem’s fears of never being able to play football were assuaged he was seldom self-conscious about his injury His left arm was somewhat shorter than his right when he stood or walked the back of his hand was at right angles to his body his thumb parallel to his thigh He couldn’t have cared less so long as he could pass and punt
　　When enough years had gone by to enable us to look back on them we sometimes discussed the events leading to his accident I maintain that the Ewells started it all but Jem who was four years my senior said it started long before that He said it began the summer Dill came to us when Dill first gave us the idea of making Boo Radley comeout
　　I said if he wanted to take a broad view of the thing it really began with AndrewJackson If General Jackson hadn’t run the Creeks up the creek Simon Finch wouldnever have paddled up the Alabama and where would we be if he hadn’t We were fartoo old to settle an argument with a fist-fight so we consulted Atticus Our father said wewere both right
　　Being Southerners it was a source of shame to some members of the family that wehad no recorded ancestors on either side of the Battle of Hastings All we had wasSimon Finch a fur-trapping apothecary from Cornwall whose piety was exceeded onlyby his stinginess In England Simon was irritated by the persecution of those who called themselves Methodists at the hands of their more liberal brethren 
    and as Simon calledhimself a Methodist he worked his way across the Atlantic to Philadelphia thence toJamaica thence to Mobile and up the Saint Stephens Mindful of John Wesley’sstrictures on the use of many words in buying and selling Simon made a pile practicingmedicine but in this pursuit he was unhappy lest he be tempted into doing what heknew was not for the glory of God as the putting on of gold and costly apparel So Simon having forgotten his teacher’s dictum on the possession of human chattels bought three slaves and with their aid established a homestead on the banks of theAlabama River some forty miles above Saint Stephens He returned to Saint Stephensonly once to find a wife and with her established a line that ran high to daughters
　　Simon lived to an impressive age and died rich
　　It was customary for the men in the family to remain on Simon’s homestead Finch’s Landing and make their living from cotton The place was self-sufficient modest incomparison with the empires around it the Landing nevertheless produced everything required to sustain life except ice wheat flour and articles of clothing supplied by river-boats from Mobile
　　Simon would have regarded with impotent fury the disturbance between the North andthe South as it left his descendants stripped of everything but their land yet the tradition of living on the land remained unbroken until well into the twentieth century when my father Atticus Finch went to Montgomery to read law and his younger brother went toBoston to study medicine Their sister Alexandra was the Finch who remained at the Landing she married a taciturn man who spent most of his time lying in a hammock bythe river wondering if his trot-lines were full
"""
result = {word:sentence.split().count(word) for word in set (sentence.split())}
result1 = sorted(result,key = lambda k : result[k])
result1.reverse()
for j in result1 :
    print(j,result[j])